export const GET_ORDERS = 'GET.ORDERS';
export const GET_ITEMS_PER_ORDER = 'GET.ITEMS.PER_ORDER';
export const CREATE_ORDER = 'CREATE.ORDER';
export const SEARCH_ORDERS = 'SEARCH.ORDERS';
export const DELETE_ORDER = 'DELETE.ORDERS';
export const UPDATE_ORDER = 'UPDATE.ORDER'